#!/bin/bash

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

echo $PWD
pwd
cd $PROJECT_DIR/app

npm run build

LAST_EXIT_CODE=$?

exit $LAST_EXIT_CODE
