#!/bin/bash

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

$PROJECT_DIR/app/node_modules/gulp/bin/gulp.js

LAST_EXIT_CODE=$?

exit $LAST_EXIT_CODE
