#!/bin/bash

set -e

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

ENV="$1"

VOLUME=""
if [ "$ENV" = "DEV" ]; then
  VOLUME="--volume $PROJECT_DIR/app/www:/var/www/pomodoro.cc/"
fi
docker run --name pomodoro-app \
  --restart=always \
  --detach=true \
  --env PRERENDER_TOKEN="$PRERENDER_TOKEN" \
  $VOLUME \
  christianfei/pomodoro-app
