#!/bin/bash

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

cd $PROJECT_DIR/app

npm test

TEST_RESULT_CODE=$?

exit $TEST_RESULT_CODE
